# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ba7c8f886fa132b476016dc3cc993691dc25036f755e9e53841f880c45a50e92aa10b0cf00eeb7537aa82111fe7c998a3b1ee3a7f2fad3895f774155231142

test:
  secret_key_base: b0d4b64265d83db4eb76ed0e8428839d2451ab8c9889f6557479a996b5ce53610e26d3c185b94062989123e982319260fdbca2dbdeb01018bb30452e5a699f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
